name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Run lints
        run: flutter analyze

      - name: Check formatting
        run: flutter format --dry-run --set-exit-if-changed .

      - name: Run tests
        run: flutter test

      - name: Android build
        run: flutter build apk --split-per-abi

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get additional dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev

      - name: Enable linux support
        run: |
          flutter config --enable-linux-desktop

      - name: Build
        run: |
          flutter build linux

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Enable windows support
        run: |
          flutter config --enable-windows-desktop

      - name: Build
        run: |
          flutter build windows

  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Build
        run: |
          flutter build web
